language: cpp
dist: trusty
compiler: clang
env:
  CMAKE_URL="https://cmake.org/files/v3.6/cmake-3.6.3-Linux-x86_64.tar.gz"
  LSLDIST_URL="https://dl.bintray.com/labstreaminglayer/LSL/"
  UBUNTU_DIST="trusty"
  LSL_VERSION="1.1.2"
  - CMakeArgs=""
script:
- mkdir -p build/install
- cd build
- $CMAKE_EXE --version
- $CMAKE_EXE -DCMAKE_BUILD_TYPE=Release -DLSL_UNIXFOLDERS=1 -DCMAKE_INSTALL_PREFIX=install -DLSL_INSTALL_ROOT=LSL/usr $CMakeArgs ../
- $CMAKE_EXE --build . --config Release --target install
matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - qt5-default
            - libboost-thread-dev
            - libboost-filesystem-dev
            - libboost-iostreams-dev
      before_script:
        - mkdir cmakebin && travis_retry wget --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmakebin
        - travis_retry wget --quiet ${LSLDIST_URL}/labstreaminglayer-liblsl{,-dev}_${LSL_VERSION}-${UBUNTU_DIST}_amd64.deb
        - dpkg -x labstreaminglayer-liblsl_${LSL_VERSION}-${UBUNTU_DIST}_amd64.deb
        - dpkg -x labstreaminglayer-liblsl-dev_${LSL_VERSION}-${UBUNTU_DIST}_amd64.deb
        - export CMAKE_EXE=$PWD/cmakebin/bin/cmake
#    - os: osx
#      before_install:
#        - brew install qt
#        - export CMAKE_PREFIX_PATH=/usr/local/opt/qt/
#        - export CMAKE_EXE=`which cmake`
deploy:
  provider: bintray
  user: tstenner
  key:
    secure: "Mm0dMP4/b0zCEu+vlGGOS9WxLpQk7NedyQSLUaNpQSG6y5q6piAVhT3de2KLcprmY6C3la51Ibuq0/6IWS1uMhofzt2xTkeNbCP61K3r+4zcEPpfszWrhelb9wbuQLN6gdnI2AnitzMoIIeyL9Br/di7Nm2Rrh6AI8viHGvLQ6gpVp16D4kM9FI78sB2BlYUu/HXYlPmakvYdixavX8I2oovOBeSOac3Ictjk5z3DIBWVQzxMHykmkwzTW3skoBxP8M98JPEc0E6H1yY3g5XM6egmw8GGvJMOWyycom1dFgF99bsb0yWkL3/GeJXpXUW4rToeb6AP/X2DRqubvuZrNeSf1k3wX9a8chU63bbEQJxRC/mQwEQ39vUYzQrgmI7kRuM3srZVmXLH9rozpOL4VIhsKSC2shf0ofh7Wd5geetSwHT5tWap9jpeEOcVGOqBSXO7Z9ZMWFKwFvomwJCgPk8niM7rWloW9FWGKOeKCfCVPQdHug99HtckYxQBb6XXJTrZJ/8jiK61eoOhMnq4TRK1fMMYhMICuSe5Qk5k3W0DJwUbiRQMh0Y6CMTJL+Mxrs+Tyk5j66IDtsJxXSsF45c9e8+Er05RKuaGhy/d9+jhDil4xs9UnRMqiR6/0/lWHYjiJXBq2jIjxUNt51HVBYoO7fu0pvXGjchHfoZRdw="
  file: .bintray.json
