version: 1.12.0.{build}
pull_requests:
  do_not_increment_build_number: true
shallow_clone: true
environment:
  VCVER: 14.0
  QTVER: 5.10.0
  QTCOMPILER: msvc2015
  ARCH: x64
  CMakeArgs: ""
install:
- cmd: >-
    appveyor DownloadFile https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip -FileName ninja.zip

    appveyor DownloadFile https://github.com/labstreaminglayer/liblsl/releases/download/1.12/liblsl_x64.zip

    7z x ninja.zip -oC:\projects\deps\ninja > nul

    7z l liblsl_x64.zip

    7z x liblsl_x64.zip

    set PATH=C:\projects\deps\ninja;%PATH%

    ninja --version
build_script:
- cmd: >-
    call "C:\Program Files (x86)\Microsoft Visual Studio %VCVER%\VC\vcvarsall.bat" %ARCH%

    mkdir build

    cd build

    cmake -G Ninja -DQt5_DIR=C:/Qt/%QTVER%/%QTCOMPILER%/lib/cmake/Qt5 -DBOOST_ROOT=C:/Libraries/boost_1_63_0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install -DLSL_INSTALL_ROOT=LSL/ %CMakeArgs% ../

    cmake --build . --config Release --target install
artifacts:
- path: build/install
  name: ${APPVEYOR_PROJECT_NAME}_%ARCH%_${APPVEYOR_BUILD_VERSION}
deploy:
- provider: BinTray
  username: tstenner
  api_key:
    secure: zcgGai0IfIlkwU5IXEvoJ/Kr+w2DbKIBJr/677Q52BPwUT0aFWSvJuZp2obpY3u5
  subject: tstenner
  repo: labstreaminglayer
  package: LSL
  override: true
